/**
 * Curated Meta Builds for ESO Trade Project
 * Provides top-tier PvE/PvP meta setups across all 7 classes and roles with authentic in-game item icons.
 */

const CURATED_BUILDS = [
    {
        "title": "Arcanist Fatecarver Beam DPS",
        "description": "Premier endgame PvE Fatecarver beam melting setup. Pairs Deadly Strike crafted/Cyrodiil jewelry & weapons with Ansuul's Torment, Velothi Ur-Mage's Amulet mythic, and Stormfist.",
        "class": "Arcanist",
        "role": "Stamina DPS",
        "author": "Skinny Cheeks",
        "source_url": "https://skinnycheeks.gg/arcanist",
        "is_curated": 1,
        "items": [
            {
                "slot_id": 0,
                "slot_name": "Head",
                "item_name": "Stormfist Helm",
                "set_name": "Stormfist",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undauntedstormatronach_head_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Tempest Island (Veteran)"
            },
            {
                "slot_id": 1,
                "slot_name": "Neck",
                "item_name": "Velothi Ur-Mage's Amulet",
                "set_name": "Velothi Ur-Mage's Amulet",
                "item_type": "Necklace",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/u38_antiquities_goldandblueshalknecklace.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Weapon Damage",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Mythic - Antiquities (Telvanni Peninsula)"
            },
            {
                "slot_id": 2,
                "slot_name": "Chest",
                "item_name": "Ansuul's Torment Jack",
                "set_name": "Perfected Ansuul's Torment",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_shirt_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Sanity's Edge (Veteran)"
            },
            {
                "slot_id": 3,
                "slot_name": "Shoulders",
                "item_name": "Stormfist Arm Cops",
                "set_name": "Stormfist",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undauntedstormatronach_shoulders_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Undaunted Pledge Master (Glirion)"
            },
            {
                "slot_id": 4,
                "slot_name": "Main Hand 1",
                "item_name": "Deadly Dagger",
                "set_name": "Deadly Strike",
                "item_type": "One-Handed Dagger",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_dagger_d.png",
                "trait_id": 8,
                "trait_name": "Nirnhoned",
                "enchantment": "Flame Damage",
                "quality": 5,
                "is_tradeable": 1,
                "source_location": "Cyrodiil Elite Vendor / Guild Traders"
            },
            {
                "slot_id": 5,
                "slot_name": "Off Hand 1",
                "item_name": "Deadly Dagger",
                "set_name": "Deadly Strike",
                "item_type": "One-Handed Dagger",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_dagger_d.png",
                "trait_id": 2,
                "trait_name": "Charged",
                "enchantment": "Poison Damage",
                "quality": 5,
                "is_tradeable": 1,
                "source_location": "Cyrodiil Elite Vendor / Guild Traders"
            },
            {
                "slot_id": 6,
                "slot_name": "Waist",
                "item_name": "Ansuul's Torment Belt",
                "set_name": "Perfected Ansuul's Torment",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_waist_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Sanity's Edge"
            },
            {
                "slot_id": 7,
                "slot_name": "Legs",
                "item_name": "Ansuul's Torment Guards",
                "set_name": "Perfected Ansuul's Torment",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_legs_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Sanity's Edge"
            },
            {
                "slot_id": 8,
                "slot_name": "Feet",
                "item_name": "Ansuul's Torment Boots",
                "set_name": "Perfected Ansuul's Torment",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_feet_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Sanity's Edge"
            },
            {
                "slot_id": 9,
                "slot_name": "Ring 1",
                "item_name": "Deadly Ring",
                "set_name": "Deadly Strike",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Weapon Damage",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Cyrodiil Elite Vendor / Guild Traders"
            },
            {
                "slot_id": 11,
                "slot_name": "Ring 2",
                "item_name": "Deadly Ring",
                "set_name": "Deadly Strike",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Weapon Damage",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Cyrodiil Elite Vendor / Guild Traders"
            },
            {
                "slot_id": 12,
                "slot_name": "Main Hand 2",
                "item_name": "Maelstrom Inferno Staff",
                "set_name": "Crushing Wall",
                "item_type": "Destruction Staff",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_staff_d.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Weapon Damage",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Arena - Maelstrom Arena (Veteran)"
            },
            {
                "slot_id": 16,
                "slot_name": "Hands",
                "item_name": "Ansuul's Torment Bracers",
                "set_name": "Perfected Ansuul's Torment",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_hands_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Sanity's Edge"
            }
        ]
    },
    {
        "title": "Dragonknight Searing Pyromancer DPS",
        "description": "High-burn single target & cleave damage configuration combining Order's Wrath crafted body with Pillar of Nirn front bar and Kjalnar's Nightmare.",
        "class": "Dragonknight",
        "role": "Magicka DPS",
        "author": "AlcastHQ",
        "source_url": "https://alcasthq.com/eso-magicka-dragonknight-build-pve",
        "is_curated": 1,
        "items": [
            {
                "slot_id": 0,
                "slot_name": "Head",
                "item_name": "Kjalnar's Nightmare Mask",
                "set_name": "Kjalnar's Nightmare",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undbonecolossus_head_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Unhallowed Grave (Veteran)"
            },
            {
                "slot_id": 1,
                "slot_name": "Neck",
                "item_name": "Necklace of the Pillar of Nirn",
                "set_name": "Pillar of Nirn",
                "item_type": "Necklace",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_neck_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Spell Damage",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Falkreath Hold"
            },
            {
                "slot_id": 2,
                "slot_name": "Chest",
                "item_name": "Order's Wrath Jerkin",
                "set_name": "Order's Wrath",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_shirt_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Crafted - High Isle"
            },
            {
                "slot_id": 3,
                "slot_name": "Shoulders",
                "item_name": "Kjalnar's Nightmare Epaulets",
                "set_name": "Kjalnar's Nightmare",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undbonecolossus_shoulder_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Undaunted Pledge Master (Urgarlag)"
            },
            {
                "slot_id": 4,
                "slot_name": "Main Hand 1",
                "item_name": "Dagger of the Pillar of Nirn",
                "set_name": "Pillar of Nirn",
                "item_type": "One-Handed Dagger",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_falkreath_dagger_a.png",
                "trait_id": 8,
                "trait_name": "Nirnhoned",
                "enchantment": "Flame Damage",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Dungeon - Falkreath Hold"
            },
            {
                "slot_id": 5,
                "slot_name": "Off Hand 1",
                "item_name": "Dagger of the Pillar of Nirn",
                "set_name": "Pillar of Nirn",
                "item_type": "One-Handed Dagger",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_falkreath_dagger_a.png",
                "trait_id": 2,
                "trait_name": "Charged",
                "enchantment": "Poison Damage",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Dungeon - Falkreath Hold"
            },
            {
                "slot_id": 6,
                "slot_name": "Waist",
                "item_name": "Order's Wrath Sash",
                "set_name": "Order's Wrath",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_medium_waist_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Crafted - High Isle"
            },
            {
                "slot_id": 7,
                "slot_name": "Legs",
                "item_name": "Order's Wrath Breeches",
                "set_name": "Order's Wrath",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_medium_legs_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Crafted - High Isle"
            },
            {
                "slot_id": 8,
                "slot_name": "Feet",
                "item_name": "Order's Wrath Shoes",
                "set_name": "Order's Wrath",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_medium_feet_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Crafted - High Isle"
            },
            {
                "slot_id": 9,
                "slot_name": "Ring 1",
                "item_name": "Ring of the Pillar of Nirn",
                "set_name": "Pillar of Nirn",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Spell Damage",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Falkreath Hold"
            },
            {
                "slot_id": 11,
                "slot_name": "Ring 2",
                "item_name": "Ring of the Pillar of Nirn",
                "set_name": "Pillar of Nirn",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Spell Damage",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Falkreath Hold"
            },
            {
                "slot_id": 12,
                "slot_name": "Main Hand 2",
                "item_name": "Maelstrom Inferno Staff",
                "set_name": "Crushing Wall",
                "item_type": "Destruction Staff",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_staff_d.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Weapon Damage",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Arena - Maelstrom Arena (Veteran)"
            },
            {
                "slot_id": 16,
                "slot_name": "Hands",
                "item_name": "Order's Wrath Gloves",
                "set_name": "Order's Wrath",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_medium_hands_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Crafted - High Isle"
            }
        ]
    },
    {
        "title": "Dragonknight Immortal Main Tank",
        "description": "The gold standard trial main tank configuration. Provides Major Vulnerability via Turning Tide, group damage scaling via Pearlescent Ward, and Major Cowardice debuffs via Nazaray.",
        "class": "Dragonknight",
        "role": "Tank",
        "author": "The Tank Club",
        "source_url": "https://thetankclub.com/eso-dragonknight-tank-build",
        "is_curated": 1,
        "items": [
            {
                "slot_id": 0,
                "slot_name": "Head",
                "item_name": "Nazaray Helm",
                "set_name": "Nazaray",
                "item_type": "Heavy Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undspriggan_head_a.png",
                "trait_id": 5,
                "trait_name": "Reinforced",
                "enchantment": "Max Health",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Shipwright's Regret (Veteran)"
            },
            {
                "slot_id": 1,
                "slot_name": "Neck",
                "item_name": "Necklace of the Turning Tide",
                "set_name": "Turning Tide",
                "item_type": "Necklace",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_neck_a.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Magicka Recovery",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Shipwright's Regret"
            },
            {
                "slot_id": 2,
                "slot_name": "Chest",
                "item_name": "Pearlescent Ward Cuirass",
                "set_name": "Pearlescent Ward",
                "item_type": "Heavy Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_shirt_d.png",
                "trait_id": 5,
                "trait_name": "Reinforced",
                "enchantment": "Max Health",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            },
            {
                "slot_id": 3,
                "slot_name": "Shoulders",
                "item_name": "Nazaray Pauldrons",
                "set_name": "Nazaray",
                "item_type": "Heavy Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/quest_summerset_completed_report.png",
                "trait_id": 5,
                "trait_name": "Reinforced",
                "enchantment": "Max Health",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Undaunted Pledge Master (Urgarlag)"
            },
            {
                "slot_id": 4,
                "slot_name": "Main Hand 1",
                "item_name": "Turning Tide Sword",
                "set_name": "Turning Tide",
                "item_type": "One-Handed Sword",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_kraken_dagger_a.png",
                "trait_id": 7,
                "trait_name": "Decisive",
                "enchantment": "Crushing",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Dungeon - Shipwright's Regret"
            },
            {
                "slot_id": 5,
                "slot_name": "Off Hand 1",
                "item_name": "Turning Tide Shield",
                "set_name": "Turning Tide",
                "item_type": "Shield",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_kraken_dagger_a.png",
                "trait_id": 5,
                "trait_name": "Reinforced",
                "enchantment": "Max Health",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Dungeon - Shipwright's Regret"
            },
            {
                "slot_id": 6,
                "slot_name": "Waist",
                "item_name": "Pearlescent Ward Girdle",
                "set_name": "Pearlescent Ward",
                "item_type": "Heavy Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_waist_a.png",
                "trait_id": 6,
                "trait_name": "Sturdy",
                "enchantment": "Max Health",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            },
            {
                "slot_id": 7,
                "slot_name": "Legs",
                "item_name": "Pearlescent Ward Greaves",
                "set_name": "Pearlescent Ward",
                "item_type": "Heavy Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_legs_a.png",
                "trait_id": 5,
                "trait_name": "Reinforced",
                "enchantment": "Max Health",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            },
            {
                "slot_id": 8,
                "slot_name": "Feet",
                "item_name": "Pearlescent Ward Sabatons",
                "set_name": "Pearlescent Ward",
                "item_type": "Heavy Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_feet_a.png",
                "trait_id": 6,
                "trait_name": "Sturdy",
                "enchantment": "Max Health",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            },
            {
                "slot_id": 9,
                "slot_name": "Ring 1",
                "item_name": "Ring of the Turning Tide",
                "set_name": "Turning Tide",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Magicka Recovery",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Shipwright's Regret"
            },
            {
                "slot_id": 11,
                "slot_name": "Ring 2",
                "item_name": "Ring of the Turning Tide",
                "set_name": "Turning Tide",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Magicka Recovery",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Shipwright's Regret"
            },
            {
                "slot_id": 12,
                "slot_name": "Main Hand 2",
                "item_name": "Maelstrom Ice Staff",
                "set_name": "Crushing Wall",
                "item_type": "Destruction Staff",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_staff_d.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Crushing",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Arena - Maelstrom Arena"
            },
            {
                "slot_id": 16,
                "slot_name": "Hands",
                "item_name": "Pearlescent Ward Gauntlets",
                "set_name": "Pearlescent Ward",
                "item_type": "Heavy Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_hands_a.png",
                "trait_id": 6,
                "trait_name": "Sturdy",
                "enchantment": "Max Health",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            }
        ]
    },
    {
        "title": "Templar Radiant Trial Healer",
        "description": "Essential endgame restoration build granting group-wide Major Courage (Spell Power Cure), ultimate regeneration (Pillager's Profit), and sustained resource return.",
        "class": "Templar",
        "role": "Healer",
        "author": "Healers Haven",
        "source_url": "https://alcasthq.com/eso-magicka-templar-healer-build-pve",
        "is_curated": 1,
        "items": [
            {
                "slot_id": 0,
                "slot_name": "Head",
                "item_name": "Symphony of Blades Mask",
                "set_name": "Symphony of Blades",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undnarlimor_head_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Depths of Malatar (Veteran)"
            },
            {
                "slot_id": 1,
                "slot_name": "Neck",
                "item_name": "Pillager's Profit Necklace",
                "set_name": "Pillager's Profit",
                "item_type": "Necklace",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_neck_a.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Magicka Recovery",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            },
            {
                "slot_id": 2,
                "slot_name": "Chest",
                "item_name": "Robe of the Spell Power Cure",
                "set_name": "Spell Power Cure",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_shirt_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - White-Gold Tower"
            },
            {
                "slot_id": 3,
                "slot_name": "Shoulders",
                "item_name": "Symphony of Blades Epaulets",
                "set_name": "Symphony of Blades",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undnarlimor_shoulder_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Undaunted Pledge Master (Urgarlag)"
            },
            {
                "slot_id": 4,
                "slot_name": "Main Hand 1",
                "item_name": "Grand Master's Restoration Staff",
                "set_name": "Grand Slam",
                "item_type": "Restoration Staff",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_dagger_d.png",
                "trait_id": 9,
                "trait_name": "Powered",
                "enchantment": "Weapon Damage",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Arena - Dragonstar Arena"
            },
            {
                "slot_id": 6,
                "slot_name": "Waist",
                "item_name": "Sash of the Spell Power Cure",
                "set_name": "Spell Power Cure",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_waist_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - White-Gold Tower"
            },
            {
                "slot_id": 7,
                "slot_name": "Legs",
                "item_name": "Breeches of the Spell Power Cure",
                "set_name": "Spell Power Cure",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_legs_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - White-Gold Tower"
            },
            {
                "slot_id": 8,
                "slot_name": "Feet",
                "item_name": "Shoes of the Spell Power Cure",
                "set_name": "Spell Power Cure",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_feet_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - White-Gold Tower"
            },
            {
                "slot_id": 9,
                "slot_name": "Ring 1",
                "item_name": "Pillager's Profit Ring",
                "set_name": "Pillager's Profit",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Magicka Recovery",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            },
            {
                "slot_id": 11,
                "slot_name": "Ring 2",
                "item_name": "Pillager's Profit Ring",
                "set_name": "Pillager's Profit",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Magicka Recovery",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            },
            {
                "slot_id": 12,
                "slot_name": "Main Hand 2",
                "item_name": "Pillager's Profit Lightning Staff",
                "set_name": "Pillager's Profit",
                "item_type": "Destruction Staff",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_staff_d.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Crushing",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            },
            {
                "slot_id": 16,
                "slot_name": "Hands",
                "item_name": "Gloves of the Spell Power Cure",
                "set_name": "Spell Power Cure",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_hands_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - White-Gold Tower"
            }
        ]
    },
    {
        "title": "Warden Glacial Frost Shaman",
        "description": "Specialized winter burst frost damage build pairing tradeable Blackwood Frostbite gear with Whorl of the Depths and Iceheart monster set.",
        "class": "Warden",
        "role": "Magicka DPS",
        "author": "Nirn Build Forge",
        "source_url": "https://eso-hub.com/en/builds/warden-frost",
        "is_curated": 1,
        "items": [
            {
                "slot_id": 0,
                "slot_name": "Head",
                "item_name": "Iceheart Mask",
                "set_name": "Iceheart",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undauntedatronach_head_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Direfrost Keep (Veteran)"
            },
            {
                "slot_id": 1,
                "slot_name": "Neck",
                "item_name": "Frostbite Necklace",
                "set_name": "Frostbite",
                "item_type": "Necklace",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_neck_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Spell Damage",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Overland - Blackwood / Guild Traders"
            },
            {
                "slot_id": 2,
                "slot_name": "Chest",
                "item_name": "Whorl of the Depths Jerkin",
                "set_name": "Whorl of the Depths",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_shirt_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            },
            {
                "slot_id": 3,
                "slot_name": "Shoulders",
                "item_name": "Iceheart Epaulets",
                "set_name": "Iceheart",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undauntedatronach_shoulders_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Undaunted Pledge Master (Glirion)"
            },
            {
                "slot_id": 4,
                "slot_name": "Main Hand 1",
                "item_name": "Frostbite Ice Staff",
                "set_name": "Frostbite",
                "item_type": "Destruction Staff",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_leyawiinmil_dagger_a.png",
                "trait_id": 2,
                "trait_name": "Charged",
                "enchantment": "Frost Damage",
                "quality": 5,
                "is_tradeable": 1,
                "source_location": "Overland - Blackwood / Guild Traders"
            },
            {
                "slot_id": 6,
                "slot_name": "Waist",
                "item_name": "Whorl of the Depths Sash",
                "set_name": "Whorl of the Depths",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_waist_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            },
            {
                "slot_id": 7,
                "slot_name": "Legs",
                "item_name": "Whorl of the Depths Breeches",
                "set_name": "Whorl of the Depths",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_legs_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            },
            {
                "slot_id": 8,
                "slot_name": "Feet",
                "item_name": "Whorl of the Depths Shoes",
                "set_name": "Whorl of the Depths",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_feet_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            },
            {
                "slot_id": 9,
                "slot_name": "Ring 1",
                "item_name": "Frostbite Ring",
                "set_name": "Frostbite",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Spell Damage",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Overland - Blackwood / Guild Traders"
            },
            {
                "slot_id": 11,
                "slot_name": "Ring 2",
                "item_name": "Frostbite Ring",
                "set_name": "Frostbite",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Spell Damage",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Overland - Blackwood / Guild Traders"
            },
            {
                "slot_id": 12,
                "slot_name": "Main Hand 2",
                "item_name": "Maelstrom Ice Staff",
                "set_name": "Crushing Wall",
                "item_type": "Destruction Staff",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_staff_d.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Weapon Damage",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Arena - Maelstrom Arena"
            },
            {
                "slot_id": 16,
                "slot_name": "Hands",
                "item_name": "Whorl of the Depths Gloves",
                "set_name": "Whorl of the Depths",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_hands_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Dreadsail Reef"
            }
        ]
    },
    {
        "title": "Solo Arena Heavy Brawler",
        "description": "Nearly unkillable solo survival build pairing Briarheart critical self-healing with Hexos' Ward shields and the Ring of the Pale Order mythic.",
        "class": "All",
        "role": "Solo / Arena",
        "author": "Hack The Minotaur",
        "source_url": "https://hacktheminotaur.com/builds/eso-solo-brawler",
        "is_curated": 1,
        "items": [
            {
                "slot_id": 0,
                "slot_name": "Head",
                "item_name": "Slimecraw Mask",
                "set_name": "Slimecraw",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undauntedcrocodile_head_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Wayrest Sewers I (Veteran)"
            },
            {
                "slot_id": 1,
                "slot_name": "Neck",
                "item_name": "Briarheart Necklace",
                "set_name": "Briarheart",
                "item_type": "Necklace",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_snowreach_medium_chest_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Weapon Damage",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Overland - Wrothgar / Guild Traders"
            },
            {
                "slot_id": 2,
                "slot_name": "Chest",
                "item_name": "Hexos' Ward Jack",
                "set_name": "Hexos' Ward",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_imperialv2med_chest_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Overland - Deadlands / Guild Traders"
            },
            {
                "slot_id": 3,
                "slot_name": "Shoulders",
                "item_name": "Hexos' Ward Epaulets",
                "set_name": "Hexos' Ward",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_imperialv2_med_shoulders_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Overland - Deadlands / Guild Traders"
            },
            {
                "slot_id": 4,
                "slot_name": "Main Hand 1",
                "item_name": "Briarheart Dagger",
                "set_name": "Briarheart",
                "item_type": "One-Handed Dagger",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_reach_dagger_c.png",
                "trait_id": 8,
                "trait_name": "Nirnhoned",
                "enchantment": "Flame Damage",
                "quality": 5,
                "is_tradeable": 1,
                "source_location": "Overland - Wrothgar / Guild Traders"
            },
            {
                "slot_id": 5,
                "slot_name": "Off Hand 1",
                "item_name": "Briarheart Dagger",
                "set_name": "Briarheart",
                "item_type": "One-Handed Dagger",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_reach_dagger_c.png",
                "trait_id": 2,
                "trait_name": "Charged",
                "enchantment": "Poison Damage",
                "quality": 5,
                "is_tradeable": 1,
                "source_location": "Overland - Wrothgar / Guild Traders"
            },
            {
                "slot_id": 6,
                "slot_name": "Waist",
                "item_name": "Hexos' Ward Belt",
                "set_name": "Hexos' Ward",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_imperialv2_med_waist_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Overland - Deadlands / Guild Traders"
            },
            {
                "slot_id": 7,
                "slot_name": "Legs",
                "item_name": "Hexos' Ward Guards",
                "set_name": "Hexos' Ward",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_imperialv2med_legs_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Overland - Deadlands / Guild Traders"
            },
            {
                "slot_id": 8,
                "slot_name": "Feet",
                "item_name": "Briarheart Boots",
                "set_name": "Briarheart",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_snowreach_medium_feet_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Overland - Wrothgar / Guild Traders"
            },
            {
                "slot_id": 9,
                "slot_name": "Ring 1",
                "item_name": "Ring of the Pale Order",
                "set_name": "Ring of the Pale Order",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/antiquities_ornate_ring_4.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Weapon Damage",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Mythic - Antiquities (Glenumbra / Wrothgar / Reach)"
            },
            {
                "slot_id": 11,
                "slot_name": "Ring 2",
                "item_name": "Briarheart Ring",
                "set_name": "Briarheart",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_reach_ring_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Weapon Damage",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Overland - Wrothgar / Guild Traders"
            },
            {
                "slot_id": 12,
                "slot_name": "Main Hand 2",
                "item_name": "Maelstrom Greatsword",
                "set_name": "Merciless Charge",
                "item_type": "Two-Handed Greatsword",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_staff_d.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Weapon Damage",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Arena - Maelstrom Arena"
            },
            {
                "slot_id": 16,
                "slot_name": "Hands",
                "item_name": "Hexos' Ward Bracers",
                "set_name": "Hexos' Ward",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_imperialv2_med_hands_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Overland - Deadlands / Guild Traders"
            }
        ]
    },
    {
        "title": "Nightblade Shadow Assassin (PvP)",
        "description": "Lethal stealth burst executioner pairing tradeable Rallying Cry with Shattered Fate for overwhelming armor penetration and Balorgh ultimate burst.",
        "class": "Nightblade",
        "role": "PvP",
        "author": "Tamriel Foundry",
        "source_url": "https://eso-pvp-builds.com/nightblade",
        "is_curated": 1,
        "items": [
            {
                "slot_id": 0,
                "slot_name": "Head",
                "item_name": "Balorgh Mask",
                "set_name": "Balorgh",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undaunted_werewolfbehemoth_head_a.png",
                "trait_id": 5,
                "trait_name": "Impenetrable",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - March of Sacrifices (Veteran)"
            },
            {
                "slot_id": 1,
                "slot_name": "Neck",
                "item_name": "Rallying Cry Necklace",
                "set_name": "Rallying Cry",
                "item_type": "Necklace",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_neck_a.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Weapon Damage",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Rewards for the Worthy / Guild Traders"
            },
            {
                "slot_id": 2,
                "slot_name": "Chest",
                "item_name": "Shattered Fate Cuirass",
                "set_name": "Shattered Fate",
                "item_type": "Heavy Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_heavy_chest_d.png",
                "trait_id": 5,
                "trait_name": "Reinforced",
                "enchantment": "Max Health",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Crafted - Apocrypha"
            },
            {
                "slot_id": 3,
                "slot_name": "Shoulders",
                "item_name": "Balorgh Arm Cops",
                "set_name": "Balorgh",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undaunted_werewolfbehemoth_shoulder_a.png",
                "trait_id": 5,
                "trait_name": "Impenetrable",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Undaunted Pledge Master (Urgarlag)"
            },
            {
                "slot_id": 4,
                "slot_name": "Main Hand 1",
                "item_name": "Rallying Cry Greatsword",
                "set_name": "Rallying Cry",
                "item_type": "Two-Handed Greatsword",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_2hsword_d.png",
                "trait_id": 8,
                "trait_name": "Nirnhoned",
                "enchantment": "Flame Damage",
                "quality": 5,
                "is_tradeable": 1,
                "source_location": "Rewards for the Worthy / Guild Traders"
            },
            {
                "slot_id": 6,
                "slot_name": "Waist",
                "item_name": "Shattered Fate Girdle",
                "set_name": "Shattered Fate",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_heavy_waist_d.png",
                "trait_id": 5,
                "trait_name": "Well-Fitted",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Crafted - Apocrypha"
            },
            {
                "slot_id": 7,
                "slot_name": "Legs",
                "item_name": "Shattered Fate Greaves",
                "set_name": "Shattered Fate",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_heavy_legs_d.png",
                "trait_id": 5,
                "trait_name": "Impenetrable",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Crafted - Apocrypha"
            },
            {
                "slot_id": 8,
                "slot_name": "Feet",
                "item_name": "Shattered Fate Sabatons",
                "set_name": "Shattered Fate",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_heavy_feet_d.png",
                "trait_id": 5,
                "trait_name": "Well-Fitted",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Crafted - Apocrypha"
            },
            {
                "slot_id": 9,
                "slot_name": "Ring 1",
                "item_name": "Rallying Cry Ring",
                "set_name": "Rallying Cry",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Weapon Damage",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Rewards for the Worthy / Guild Traders"
            },
            {
                "slot_id": 11,
                "slot_name": "Ring 2",
                "item_name": "Rallying Cry Ring",
                "set_name": "Rallying Cry",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Weapon Damage",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Rewards for the Worthy / Guild Traders"
            },
            {
                "slot_id": 12,
                "slot_name": "Main Hand 2",
                "item_name": "Vateshran Ice Staff",
                "set_name": "Wrath of Elements",
                "item_type": "Destruction Staff",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_staff_d.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Berserker",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Arena - Vateshran Hollows (Veteran)"
            },
            {
                "slot_id": 16,
                "slot_name": "Hands",
                "item_name": "Shattered Fate Bracers",
                "set_name": "Shattered Fate",
                "item_type": "Medium Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_medium_hands_d.png",
                "trait_id": 5,
                "trait_name": "Impenetrable",
                "enchantment": "Max Stamina",
                "quality": 4,
                "is_tradeable": 1,
                "source_location": "Crafted - Apocrypha"
            }
        ]
    },
    {
        "title": "Necromancer Catalyst Raid Support",
        "description": "Vital 12-person raid composition build buffing entire trial teams with +15% Critical Damage (Elemental Catalyst) and Major Slayer (Master Architect).",
        "class": "Necromancer",
        "role": "Magicka DPS",
        "author": "The Tank Club",
        "source_url": "https://eso-hub.com/en/builds/necromancer-catalyst",
        "is_curated": 1,
        "items": [
            {
                "slot_id": 0,
                "slot_name": "Head",
                "item_name": "Magma Incarnate Mask",
                "set_name": "Magma Incarnate",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_undearthinvarnate_head_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - The Dread Cellar (Veteran)"
            },
            {
                "slot_id": 1,
                "slot_name": "Neck",
                "item_name": "Necklace of the Master Architect",
                "set_name": "Master Architect",
                "item_type": "Necklace",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_neck_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Spell Damage",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Halls of Fabrication"
            },
            {
                "slot_id": 2,
                "slot_name": "Chest",
                "item_name": "Elemental Catalyst Jerkin",
                "set_name": "Elemental Catalyst",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_shirt_d.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Stone Garden"
            },
            {
                "slot_id": 3,
                "slot_name": "Shoulders",
                "item_name": "Spaulder of Ruin",
                "set_name": "Spaulder of Ruin",
                "item_type": "Shoulders",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_razorhorndaedric_shoulder_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Mythic - Antiquities (Deadlands)"
            },
            {
                "slot_id": 4,
                "slot_name": "Main Hand 1",
                "item_name": "Master Architect Lightning Staff",
                "set_name": "Master Architect",
                "item_type": "Destruction Staff",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_clockwork_staff_a.png",
                "trait_id": 2,
                "trait_name": "Charged",
                "enchantment": "Shock Damage",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Trial - Halls of Fabrication"
            },
            {
                "slot_id": 6,
                "slot_name": "Waist",
                "item_name": "Elemental Catalyst Sash",
                "set_name": "Elemental Catalyst",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_waist_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Stone Garden"
            },
            {
                "slot_id": 7,
                "slot_name": "Legs",
                "item_name": "Elemental Catalyst Breeches",
                "set_name": "Elemental Catalyst",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_legs_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Stone Garden"
            },
            {
                "slot_id": 8,
                "slot_name": "Feet",
                "item_name": "Elemental Catalyst Shoes",
                "set_name": "Elemental Catalyst",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_feet_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Stone Garden"
            },
            {
                "slot_id": 9,
                "slot_name": "Ring 1",
                "item_name": "Ring of the Master Architect",
                "set_name": "Master Architect",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Spell Damage",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Halls of Fabrication"
            },
            {
                "slot_id": 11,
                "slot_name": "Ring 2",
                "item_name": "Ring of the Master Architect",
                "set_name": "Master Architect",
                "item_type": "Ring",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_ring_a.png",
                "trait_id": 3,
                "trait_name": "Bloodthirsty",
                "enchantment": "Spell Damage",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Trial - Halls of Fabrication"
            },
            {
                "slot_id": 12,
                "slot_name": "Main Hand 2",
                "item_name": "Maelstrom Inferno Staff",
                "set_name": "Crushing Wall",
                "item_type": "Destruction Staff",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_staff_d.png",
                "trait_id": 4,
                "trait_name": "Infused",
                "enchantment": "Weapon Damage",
                "quality": 5,
                "is_tradeable": 0,
                "source_location": "Arena - Maelstrom Arena"
            },
            {
                "slot_id": 16,
                "slot_name": "Hands",
                "item_name": "Elemental Catalyst Gloves",
                "set_name": "Elemental Catalyst",
                "item_type": "Light Armor",
                "item_icon": "https://esoicons.uesp.net/esoui/art/icons/gear_breton_light_hands_a.png",
                "trait_id": 1,
                "trait_name": "Divines",
                "enchantment": "Max Magicka",
                "quality": 4,
                "is_tradeable": 0,
                "source_location": "Dungeon - Stone Garden"
            }
        ]
    }
];

/**
 * Seeds the database with curated builds if none exist or resets them on version bump.
 */
async function seedCuratedMetaBuilds(db) {
    return new Promise((resolve, reject) => {
        db.get("SELECT COUNT(*) as count FROM builds WHERE is_curated = 1;", async (err, row) => {
            if (err) return reject(err);

            // If curated builds already exist, update item icons to ensure 100% authenticity
            if (row && row.count >= 8) {
                console.log(`[Builds] Found ${row.count} curated meta builds. Updating item icons...`);
                for (const b of CURATED_BUILDS) {
                    for (const item of b.items) {
                        db.run(
                            "UPDATE build_items SET item_icon = ? WHERE set_name = ? AND slot_id = ?;",
                            [item.item_icon, item.set_name, item.slot_id]
                        );
                    }
                }
                return resolve();
            }

            console.log("[Builds] Seeding curated meta builds with item icons into database...");
            db.serialize(() => {
                for (const build of CURATED_BUILDS) {
                    db.run(
                        `INSERT INTO builds (title, description, class, role, author, source_url, is_curated)
                         VALUES (?, ?, ?, ?, ?, ?, 1);`,
                        [build.title, build.description, build.class, build.role, build.author, build.source_url],
                        function (bErr) {
                            if (bErr) {
                                console.error("Error seeding build:", bErr.message);
                                return;
                            }
                            const buildId = this.lastID;
                            for (const item of build.items) {
                                db.run(
                                    `INSERT OR REPLACE INTO build_items 
                                     (build_id, slot_id, slot_name, item_name, set_name, item_type, item_icon, trait_id, trait_name, enchantment, quality, is_tradeable, source_location)
                                     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);`,
                                    [
                                        buildId, item.slot_id, item.slot_name, item.item_name, item.set_name,
                                        item.item_type, item.item_icon, item.trait_id || 1, item.trait_name || "Divines",
                                        item.enchantment || "Max Magicka", item.quality || 4, item.is_tradeable, item.source_location
                                    ]
                                );
                            }
                        }
                    );
                }
                resolve();
            });
        });
    });
}

module.exports = {
    CURATED_BUILDS,
    seedCuratedMetaBuilds
};
